name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman globally
        run: npm install -g newman newman-reporter-htmlextra

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./api-tests

      - name: Run All Postman Collections (PowerShell)
        shell: pwsh
        run: .\run-all-tests.ps1

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: api-tests/reports/**/*.html 